version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: nutrilud
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: zac033
        ports:
            - "3306:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
