name: Laravel Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: nutrilud
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: zac033
        ports:
          - 3306:3306

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Construir la imagen de Docker
      - name: Build Docker image
        run: |
          docker build -t laravel-backend .

      # Instalar dependencias con Composer
      - name: Install dependencies
        run: |
          docker run --rm -v $(pwd):/var/www laravel-backend composer install --no-interaction --prefer-dist --optimize-autoloader

      # Correr migraciones
      - name: Run migrations
        run: |
          docker run --rm \
            --env DB_HOST=${{ secrets.DB_HOST }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --env DB_DATABASE=${{ secrets.DB_DATABASE }} \
            --env DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -v $(pwd):/var/www \
            laravel-backend php artisan migrate

      # Correr pruebas
      - name: Run tests
        run: |
          docker run --rm -v $(pwd):/var/www laravel-backend php artisan test
