name: Deploy Nutrilud-BackEnd- to EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verificar el código y descargar dependencias
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, curl, xml, zip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      # Paso 2: Configurar la clave SSH y permitir la conexión
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Paso 3: Subir los archivos al servidor EC2
      - name: Deploy to EC2
        run: |
          echo "Conectando a la instancia EC2..."
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Asegurarse de que los comandos necesarios estén instalados
            sudo apt-get update
            sudo apt-get install -y git php-cli php-mbstring unzip curl apache2

            # Crear la ruta del proyecto si no existe
            mkdir -p /var/www/${{ secrets.PROJECT_PATH }}

            # Navegar a la ruta del proyecto
            cd /var/www/${{ secrets.PROJECT_PATH }}

            # Clonar el repositorio si no existe
            if [ ! -d ".git" ]; then
              git clone https://github.com/AbrahamCoco/Nutrilud-BackEnd-.git .
            fi

            # Actualizar el repositorio
            git pull origin master

            # Instalar dependencias de Composer
            composer install --no-dev --optimize-autoloader

            # Cachear configuración y rutas
            php artisan config:cache
            php artisan route:cache

            # Reiniciar Apache
            sudo systemctl restart apache2
          EOF

      # Paso 4: Limpiar las dependencias no necesarias (opcional)
      - name: Clean up
        run: |
          rm -rf /var/www/${{ secrets.PROJECT_PATH }}/storage/*
          rm -rf /var/www/${{ secrets.PROJECT_PATH }}/bootstrap/cache/*
