name: Nutrilud-BackEnd-

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Desplegar a EC2
      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}
          PEM_FILE: ${{ secrets.PEM_FILE }}
        run: |
          scp -o StrictHostKeyChecking=no -i $PEM_FILE -r $(pwd) $EC2_USER@$EC2_IP:/var/www/Nutrilud-BackEnd-
          ssh -o StrictHostKeyChecking=no -i $PEM_FILE $EC2_USER@$EC2_IP "cd /var/www/Nutrilud-BackEnd- && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"
